#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
# yabai -m config mouse_modifier             fn
yabai -m config window_border                off
yabai -m config window_border_blur           off

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0

# Emacs doesn't play well with yabai
yabai -m rule --add app=Emacs manage=on

# give some space for the status bar
# yabai -m config top_padding 26
yabai -m config external_bar all:20:0

echo "yabai configuration loaded.."
